### PR TITLE
Updating Sentry config.yaml to support actual yaml.

### PR DESCRIPTION
**Pull request by DandyDeveloper**
I honestly am not sure if we're too far gone to actually do this... But we really should support YAML in the `configYml` option. 

Make pipelining and stuff MUCH easier using this.

### CODE REVIEW

**Comment by Mokto** [comment]
Yeah, the idea was to maintain compatibility with the old chart.

Now it's not the case anymore, but I'm a bit reluctant to change a major version just for that.

Maybe we should use this opportunity to separate the 4 services definitions at the same time ?

**Comment by DandyDeveloper** [comment]
> Maybe we should use this opportunity to separate the 4 services definitions at the same time ?

@Mokto Can you expand on this

**Comment by Mokto** [comment]
Talking about this issue : https://github.com/sentry-kubernetes/charts/issues/134

**Comment by DandyDeveloper** [comment]
@Mokto I definitely think we should consider making "Larger" changes and noting the breaking changes in release notes.

This change for example is just very appropriate to me.

**Comment by DandyDeveloper** [comment]
@Mokto Do we wanna do this?

**Comment by Mokto** [comment]
Yes, I'm going to merge it and deploy 6.0.0 with https://github.com/sentry-kubernetes/charts/pull/198 which is also breaking.

**Pull request merged**
