### PR TITLE
Recovery support multi hosts and ports of external kafka cluster

### PR DESCRIPTION
**Pull request by MemberIT**
Fix issue https://github.com/sentry-kubernetes/charts/issues/1584

### CODE REVIEW

**Comment by MemberIT** [comment]
Hi @Mokto
Sorry, but i can't understand how to fix [this](https://github.com/sentry-kubernetes/charts/actions/runs/11591483488/job/32271308503?pr=1588)

**Comment by Mokto** [comment]
Doesn't matter, no worries.

**Comment by patsevanton** [comment]
@MemberIT Do you have ready terraform kafka code for yandex cloud ? If not, okay.

**Comment by nadecancode** [comment]
~~I think this looks right.~~

Is it possible to move the configuration somewhere else? Moving kafka hosts & ports to `cluster` will break the existing configurations.

**Comment by MemberIT** [comment]
> @MemberIT Do you have ready terraform kafka code for yandex cloud ? If not, okay.

@patsevanton, I don't have any ready-made terraform code to quickly test this.

**Comment by MemberIT** [comment]
> ~I think this looks right.~
> 
> Is it possible to move the configuration somewhere else? Moving kafka hosts & ports to `cluster` will break the existing configurations.

Actually, until version sentry-v25.19.0, externalKafka could be either a hash or an array, which is very strange and prevents the introduction of additional values (in the future, we can add support for SSL authentication for kafka). While preparing the kafka sasl auth feature for sentry-v25.19.0, I missed that externalKafka can be an array because it was documented only in the README.md.

I could restore backward compatibility in this PR to how it was before sentry-v25.19.0 by combining variables, which seems logical:

```yaml
externalKafka:
  compression:
    type:  # 'gzip', 'snappy', 'lz4', 'zstd'
  message:
    max:
      bytes: 50000000
  socket:
    timeout:
      ms: 1000
```
and
```yaml
sentry:
  kafka:
    message:
      max:
        bytes: 50000000
    compression:
      type:  # 'gzip', 'snappy', 'lz4', 'zstd'
    socket:
      timeout:
        ms: 1000
```
But these variables need to be separated:
```yaml
externalKafka:
  sasl:
    mechanism: None  # PLAIN, SCRAM-256, SCRAM-512
    username: None
    password: None
  security:
    protocol: plaintext  # 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL', and 'SSL'
```
like:
```yaml
externalKafkaSASL:
  mechanism: None  # PLAIN, SCRAM-256, SCRAM-512
  username: None
  password: None
externalKafkaSecurity:
  protocol: plaintext  # 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL', and 'SSL'
```

Is it worth making these changes to guarantee backward compatibility?

It seems normal to me that the structure of values passed into the chart can change from version to version.

I am open to any suggestions on the PR.

**Comment by patsevanton** [comment]
I'm leaning towards
```yaml
externalKafka:
  sasl:
    mechanism: None  # PLAIN, SCRAM-256, SCRAM-512
    username: None
    password: None
  security:
    protocol: plaintext  # 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL', and 'SSL'
```

**Comment by patsevanton** [comment]
@MemberIT Hello! i created k8s and kafka by repository https://github.com/patsevanton/sentry-with-external-kafka

and set values.yaml
```yaml
externalKafka:
  cluster:
    - host: "rc1a-ah3jsas127q8ng11.mdb.yandexcloud.net"
      port: 9092
    - host: "rc1b-c4pv8ou9atkl61b4.mdb.yandexcloud.net"
      port: 9092
    - host: "rc1d-h2gh8089paovc814.mdb.yandexcloud.net"
      port: 9092
  compression:
    type:  # 'gzip', 'snappy', 'lz4', 'zstd'
  message:
    max:
      bytes: 50000000
  sasl:
    mechanism: SCRAM-SHA-512
    username: sentry
    password: your_password_here
  security:
    protocol: SASL_PLAINTEXT
  socket:
    timeout:
      ms: 1000
```

Work!
and
values.yaml
```yaml
externalKafka:
  host: "rc1a-ah3jsas127q8ng11.mdb.yandexcloud.net"
  port: 9092
  compression:
    type:  # 'gzip', 'snappy', 'lz4', 'zstd'
  message:
    max:
      bytes: 50000000
  sasl:
    mechanism: SCRAM-SHA-512
    username: sentry
    password: your_password_here
  security:
    protocol: SASL_PLAINTEXT
  socket:
    timeout:
      ms: 1000
```
work!

FYI @Mokto

**Comment by patsevanton** [comment]
I try install sentry with values.yaml
```
externalKafka:
  host: "rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net"
  port: 9092
  sasl:
    mechanism: PLAIN  # PLAIN,SCRAM-256,SCRAM-512
    username: sentry
    password: your_password_here
```

and get error:
```
sentry-snuba-db-init-ctwcv snuba-init cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed to get metadata: Local: Timed out"}
sentry-snuba-db-init-ctwcv snuba-init 2024-11-03 08:51:24,629 Attempting to connect to Kafka (attempt 58)...
sentry-snuba-db-init-ctwcv snuba-init %4|1730623884.978|FAIL|rdkafka#producer-59| [thrd:rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap]: rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 344ms in state UP)
sentry-snuba-db-init-ctwcv snuba-init %4|1730623885.435|FAIL|rdkafka#producer-59| [thrd:rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap]: rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 454ms in state UP, 1 identical error(s) suppressed)
sentry-snuba-db-init-ctwcv snuba-init 2024-11-03 08:51:25,630 Connection to Kafka failed (attempt 58)
sentry-snuba-db-init-ctwcv snuba-init Traceback (most recent call last):
sentry-snuba-db-init-ctwcv snuba-init   File "/usr/src/snuba/snuba/cli/bootstrap.py", line 76, in bootstrap
sentry-snuba-db-init-ctwcv snuba-init     client.list_topics(timeout=1)
sentry-snuba-db-init-ctwcv snuba-init   File "/usr/local/lib/python3.11/site-packages/confluent_kafka/admin/__init__.py", line 603, in list_topics
sentry-snuba-db-init-ctwcv snuba-init     return super(AdminClient, self).list_topics(*args, **kwargs)
sentry-snuba-db-init-ctwcv snuba-init            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-snuba-db-init-ctwcv snuba-init cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed to get metadata: Local: Timed out"}
sentry-snuba-db-init-ctwcv snuba-init 2024-11-03 08:51:26,631 Attempting to connect to Kafka (attempt 59)...
sentry-snuba-db-init-ctwcv snuba-init %4|1730623886.983|FAIL|rdkafka#producer-60| [thrd:rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap]: rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 344ms in state UP)
sentry-snuba-db-init-ctwcv snuba-init %4|1730623887.435|FAIL|rdkafka#producer-60| [thrd:rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap]: rc1a-sr63ad20sbm49h38.mdb.yandexcloud.net:9092/bootstrap: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 450ms in state UP, 1 identical error(s) suppressed)
```

**Comment by patsevanton** [comment]
@MemberIT if use
```
externalKafka:
  - host: "rc1a-ah3jsas127q8ng11.mdb.yandexcloud.net"
    port: 9092
  - host: "rc1b-c4pv8ou9atkl61b4.mdb.yandexcloud.net"
    port: 9092
  - host: "rc1d-h2gh8089paovc814.mdb.yandexcloud.net"
    port: 9092
  compression:
    type:  zstd # 'gzip', 'snappy', 'lz4', 'zstd'
```
i get error:
```
helm install -n test --wait sentry . --values values.yaml --timeout=1000s
Error: INSTALLATION FAILED: failed to parse values.yaml: error converting YAML to JSON: yaml: line 2187: did not find expected '-' indicator
```

**Comment by patsevanton** [comment]
@MemberIT If use
```yaml
externalKafka:
  cluster:
    ## List of Hostnames or ip addresses and ports of external kafka
    - host: "rc1a-ah3jsas127q8ng11.mdb.yandexcloud.net"
      port: 9092
    - host: "rc1b-c4pv8ou9atkl61b4.mdb.yandexcloud.net"
      port: 9092
    - host: "rc1d-h2gh8089paovc814.mdb.yandexcloud.net"
      port: 9092
  compression:
    type:  # 'gzip', 'snappy', 'lz4', 'zstd'
```
I get error
```
helm install -n test --wait sentry . --values values.yaml --timeout=1000s
Error: INSTALLATION FAILED: execution error at (sentry/templates/sentry/subscription-consumer/transactions/deployment-sentry-subscription-consumer-transactions.yaml:33:33): A valid .Values.externalKafka.host is required
```

**Comment by Lattenike** [comment]
This issue isn't add to tag 26.4.0? When will you add this issue to tag?

**Comment by Lattenike** [comment]
Now my sentry version is 26.3.0, I can't use multi hosts and ports of external kafka ,and I'm meeting error "snuba.migrations.errors.MigrationInProgress: events_analytics_platform: 0009_drop_index_attribute_key_buckets_1_19", if this issue affect sentry-snuba-migrate.

**Comment by Lattenike** [comment]
Now I just do "kubectl delete job sentry-snuba-migrate" to skip snuba-migrate

**Comment by Lattenike** [comment]
Just now , my UI service and other service is still working healthly , if snuba-migrate is not  prerequisite.

**Comment by nadecancode** [comment]
> Now my sentry version is 26.3.0, I can't use multi hosts and ports of external kafka ,and I'm meeting error "snuba.migrations.errors.MigrationInProgress: events_analytics_platform: 0009_drop_index_attribute_key_buckets_1_19", if this issue affect sentry-snuba-migrate.

It got stuck but I don't think it's related to this PR. More likely your clickhouse had some issues and I would retry this migration by creating a snuba debug container, exec into it and reverse this migration.

**Comment by patsevanton** [comment]
@Mokto is it possible to merge this pull request ?

**Comment by iscultas** [comment]
@MemberIT @Mokto is it possible to backport these changes into v25? Because it is impossible to upgrade to v26 when config is broken in v25.19.0

**Comment by Mokto** [comment]
Sorry but that would be super annoying to do with the current build system.

Why don't you do it manually in your project?

**Comment by iscultas** [comment]
> Sorry but that would be super annoying to do with the current build system.
> 
> Why don't you do it manually in your project?

Already did, but it is a nasty hack regarding that the chart is set up in Terraform as a part of a module.

**Comment by MemberIT** [comment]
> @MemberIT @Mokto is it possible to backport these changes into v25? Because it is impossible to upgrade to v26 when config is broken in v25.19.0

@Lattenike, I reviewed the changes in helm chart from [sentry-v25.18.0](https://github.com/sentry-kubernetes/charts/tree/sentry-v25.18.0) to [sentry-v26.5.0](https://github.com/sentry-kubernetes/charts/tree/sentry-v26.5.0), and it seems that it might be possible to use the chart from [sentry-v26.5.0](https://github.com/sentry-kubernetes/charts/tree/sentry-v26.5.0) specifying  [Sentry version](https://github.com/sentry-kubernetes/charts/blob/develop/charts/sentry/Chart.yaml#L6) as 24.8.0 in helm chart to upgrade Sentry to 24.8.0, and then use it as is to upgrade Sentry to 24.9.0

**Comment by Mokto** [comment]
That's a good idea.

**Comment by MemberIT** [comment]
> That's a good idea.

@Mokto, I added a note in `CHANGELOG.md`. If this workaround proves effective, we can merge [this PR](https://github.com/sentry-kubernetes/charts/pull/1598) so that the workaround is documented

**Comment by iscultas** [comment]
@MemberIT @Mokto today tried to upgrade to 26.5.0 and faced with `Error: execution error at (sentry/templates/sentry/subscription-consumer/transactions/deployment-sentry-subscription-consumer-transactions.yaml:33:33): A valid .Values.externalKafka.host is required` Probably required condition must be remove here https://github.com/sentry-kubernetes/charts/blame/ff096da0b7cc94a35e2891550426c8d61cf700d6/charts/sentry/templates/_helper.tpl#L422

**Comment by MemberIT** [comment]
> @MemberIT @Mokto today tried to upgrade to 26.5.0 and faced with `Error: execution error at (sentry/templates/sentry/subscription-consumer/transactions/deployment-sentry-subscription-consumer-transactions.yaml:33:33): A valid .Values.externalKafka.host is required` Probably required condition must be remove here https://github.com/sentry-kubernetes/charts/blame/ff096da0b7cc94a35e2891550426c8d61cf700d6/charts/sentry/templates/_helper.tpl#L422

@iscultas, You need to change `externalKafka.host` to `externalKafka.cluster`
[README.md](https://github.com/sentry-kubernetes/charts/blob/sentry-v26.5.0/charts/sentry/README.md#external-kafka-configuration)
Before (for sentry-v25.18.0):
```
externalKafka:
  - host: "233.5.100.28"
    port: 9092
  - host: "kafka-confluent-2"
    port: 9093
  - host: "kafka-confluent-3"
    port: 9094
```
After (for sentry-v26.5.0):
```
externalKafka:
  cluster:
    - host: "233.5.100.28"
      port: 9092
    - host: "kafka-confluent-2"
      port: 9093
    - host: "kafka-confluent-3"
      port: 9094
```

**Comment by iscultas** [comment]
> > @MemberIT @Mokto today tried to upgrade to 26.5.0 and faced with `Error: execution error at (sentry/templates/sentry/subscription-consumer/transactions/deployment-sentry-subscription-consumer-transactions.yaml:33:33): A valid .Values.externalKafka.host is required` Probably required condition must be remove here https://github.com/sentry-kubernetes/charts/blame/ff096da0b7cc94a35e2891550426c8d61cf700d6/charts/sentry/templates/_helper.tpl#L422
> 
> 
> 
> @iscultas, You need to change `externalKafka.host` to `externalKafka.cluster`
> 
> [README.md](https://github.com/sentry-kubernetes/charts/blob/sentry-v26.5.0/charts/sentry/README.md#external-kafka-configuration)
> 
> Before (for sentry-v25.18.0):
> 
> ```
> 
> externalKafka:
> 
>   - host: "233.5.100.28"
> 
>     port: 9092
> 
>   - host: "kafka-confluent-2"
> 
>     port: 9093
> 
>   - host: "kafka-confluent-3"
> 
>     port: 9094
> 
> ```
> 
> After (for sentry-v26.5.0):
> 
> ```
> 
> externalKafka:
> 
>   cluster:
> 
>     - host: "233.5.100.28"
> 
>       port: 9092
> 
>     - host: "kafka-confluent-2"
> 
>       port: 9093
> 
>     - host: "kafka-confluent-3"
> 
>       port: 9094
> 
> ```
> 
> 

Yea mate. Already did it. And I am getting this error. Strange

**Comment by MemberIT** [comment]
@iscultas
It seems to me, this error might occur if there is a typo in the word `cluster` or if the `cluster` key was lost due to indentation issues in your custom `values.yaml`.

**Pull request merged**
