### PR TITLE
feat: dependency update before push chart

### LINKED ISSUE #1282: Clickhouse helm chart not updated in release 23.1.0
Version of Clickhouse helm chart in Chart.yaml:
```yml
dependencies:
  ...
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.9.0
    condition: clickhouse.enabled
```

Version in helm chart sentry-23.1.0.tar.gz:

Cliskhouse Chart.yaml
```yml
version: 3.7.1
```

Maybe because in [this](https://github.com/sentry-kubernetes/charts/tree/develop/sentry/charts) directory old chart presented.

### PR DESCRIPTION
**Pull request by alexandrovas**
We need to pull dependencies before package helm chart. Closes https://github.com/sentry-kubernetes/charts/issues/1282

### CODE REVIEW

**Comment by alexandrovas** [comment]
@Mokto Hi! Can you pls review these changes?

**Comment by Mokto** [comment]
I think deleting the charts folder should be enough ? renovate takes care of updating the lock file

**Comment by alexandrovas** [comment]
@Mokto Unfortunately I'm not familiar with how renovate works. Can you please indicate what potential problems my changes create?

**Comment by Mokto** [comment]
You can just remove your changes on the yaml files and everything should be fine.

**Comment by alexandrovas** [comment]
@Mokto No, linters will be failed. See: https://github.com/sentry-kubernetes/charts/actions/runs/9205800428/job/25322261629

And if `dependency update` task will not executed before build chart, then resulting chart will not contains dependencies.

**Review by Mokto — APPROVED** [review]

**Pull request merged**
