### PR TITLE
feat: update sentry appVersion to 24.8.0

### PR DESCRIPTION
**Pull request by patsevanton**
Description
This pull request updates the appVersion of the Sentry Helm chart from 24.7.1 to 24.8.0.

```
k get pod -n test
NAME                                                              READY   STATUS    RESTARTS      AGE
sentry-billing-metrics-consumer-79bdf568c9-grndc                  1/1     Running   0             10m
sentry-clickhouse-0                                               1/1     Running   0             21m
sentry-cron-776bdb4bbd-xkdt5                                      1/1     Running   2 (20m ago)   21m
sentry-generic-metrics-consumer-5dbf68f675-n8rh5                  1/1     Running   0             10m
sentry-ingest-consumer-attachments-54bff4bc85-fw7xp               1/1     Running   0             10m
sentry-ingest-consumer-events-7456d8c96b-95cp9                    1/1     Running   0             10m
sentry-ingest-consumer-transactions-5988dcc546-vvtj8              1/1     Running   0             10m
sentry-ingest-monitors-6b89cdb4f7-57mn4                           1/1     Running   0             10m
sentry-ingest-occurrences-7d7dbf948f-drns8                        1/1     Running   0             10m
sentry-ingest-replay-recordings-68ffdf8d85-8tqtm                  1/1     Running   0             10m
sentry-issue-occurrence-consumer-5fcb74d78-nxbpr                  1/1     Running   0             9m50s
sentry-kafka-controller-0                                         1/1     Running   0             21m
sentry-kafka-controller-1                                         1/1     Running   0             21m
sentry-kafka-controller-2                                         1/1     Running   0             21m
sentry-metrics-consumer-64cb5969ff-rplnz                          1/1     Running   0             10m
sentry-nginx-86d6c867f8-fmglf                                     1/1     Running   0             21m
sentry-post-process-forward-errors-bcdd9bcbb-9h49f                1/1     Running   0             10m
sentry-post-process-forward-issue-platform-5585db5b95-rjd95       1/1     Running   0             10m
sentry-post-process-forward-transactions-cc7ff69cc-rhv5k          1/1     Running   0             10m
sentry-rabbitmq-0                                                 1/1     Running   0             21m
sentry-relay-cd9fbf484-mcscq                                      1/1     Running   0             9m45s
sentry-sentry-postgresql-0                                        1/1     Running   0             21m
sentry-sentry-redis-master-0                                      1/1     Running   0             21m
sentry-sentry-redis-replicas-0                                    1/1     Running   0             21m
sentry-snuba-api-6c674b6797-7bhd2                                 1/1     Running   0             21m
sentry-snuba-consumer-b9b8b9dd8-979gw                             1/1     Running   0             10m
sentry-snuba-generic-metrics-counters-consumer-6c565457f8-n5jgl   1/1     Running   0             9m57s
sentry-snuba-generic-metrics-distributions-consumer-64d78fslfj6   1/1     Running   0             9m56s
sentry-snuba-generic-metrics-sets-consumer-58dc8b9494-jvd99       1/1     Running   0             9m55s
sentry-snuba-group-attributes-consumer-7cc6bc9fdd-9rfs6           1/1     Running   0             9m54s
sentry-snuba-metrics-consumer-c98596579-pzbpv                     1/1     Running   0             9m54s
sentry-snuba-outcomes-billing-consumer-7cc6d455bb-9ndwq           1/1     Running   0             9m53s
sentry-snuba-outcomes-consumer-78b859867f-8z2hl                   1/1     Running   0             9m49s
sentry-snuba-replacer-fd9545b5c-prqts                             1/1     Running   0             9m48s
sentry-snuba-replays-consumer-77555c647c-xjsdn                    1/1     Running   0             9m52s
sentry-snuba-spans-consumer-f85597476-gkmm2                       1/1     Running   0             9m51s
sentry-snuba-subscription-consumer-events-59cfd68856-sgt2x        1/1     Running   0             9m47s
sentry-snuba-subscription-consumer-metrics-d4f645879-2k54n        1/1     Running   0             9m47s
sentry-snuba-subscription-consumer-transactions-854cf7dfc44zpll   1/1     Running   0             9m46s
sentry-snuba-transactions-consumer-68d5f86dfd-wnkdh               1/1     Running   0             9m50s
sentry-subscription-consumer-events-644f989f99-pqpqk              1/1     Running   0             10m
sentry-subscription-consumer-generic-metrics-858f45d868-n5t98     1/1     Running   0             9m59s
sentry-subscription-consumer-metrics-665b79b996-bv8nx             1/1     Running   0             9m58s
sentry-subscription-consumer-transactions-7645d86cdc-m7hhn        1/1     Running   0             9m57s
sentry-web-7ccd66948-tvwv8                                        1/1     Running   1 (20m ago)   21m
sentry-worker-79669599cc-z57nd                                    1/1     Running   2 (20m ago)   21m
sentry-zookeeper-clickhouse-0                                     1/1     Running   0             21m
```

```
k get deploy -n test -o yaml| grep "image: getsentry/sentry" | uniq
          image: getsentry/sentry:24.8.0
```

```
k get sts -n test -o yaml| grep "image: clickhouse/clickhouse-server"
          image: clickhouse/clickhouse-server:23.3.19.32
```

### CODE REVIEW

**Comment by Mokto** [comment]
Nice, we can't move to 24.9.0 or 24.10.0 directly?

**Comment by patsevanton** [comment]
I would like to use different tags with different versions of sentry to understand where suddenly a new error appears.

**Comment by Mokto** [comment]
Makes sense!

**Comment by fcuello-fudo** [comment]
> Nice, we can't move to 24.9.0 or 24.10.0 directly?

Also, according to https://develop.sentry.dev/self-hosted/releases/#hard-stops you must upgrade to 24.8.0 first, before upgrading to  24.9.0 or 24.10.0.

Probably this needs to be added to the README here and probably bump the chart major version to reflect that.

FWIW, I'm already running 24.10.0 using this chart and changing the image tags, after going through the hard stops, with no big issues.

**Comment by bmassemin** [comment]
Snuba is still in `24.7.1`, is it normal? Web is correctly set to `24.8.0`
EDIT: Never mind, the chart is not fully deployed

**Comment by patsevanton** [comment]
@bmassemin 
install
```
helm install sentry -n test sentry/sentry --version 25.20.0  --wait --timeout=1000s
coalesce.go:237: warning: skipped value for kafka.config: Not a table.
NAME: sentry
LAST DEPLOYED: Thu Oct 24 15:10:14 2024
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
* When running upgrades, make sure to give back the `system.secretKey` value.

kubectl -n test get configmap sentry-sentry -o json | grep -m1 -Po '(?<=system.secret-key: )[^\\]*'
```

get image
```
kubectl get pods -n test -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.containers[*].image}{"\n"}{end}'
sentry-billing-metrics-consumer-79bdf568c9-pc7bm	getsentry/sentry:24.8.0
sentry-clickhouse-0	clickhouse/clickhouse-server:23.3.19.32
sentry-cron-776bdb4bbd-n2rkx	getsentry/sentry:24.8.0
sentry-generic-metrics-consumer-5dbf68f675-97gkg	getsentry/sentry:24.8.0
sentry-ingest-consumer-attachments-54bff4bc85-9zplg	getsentry/sentry:24.8.0
sentry-ingest-consumer-events-7456d8c96b-dnwbr	getsentry/sentry:24.8.0
sentry-ingest-consumer-transactions-5988dcc546-d5dp2	getsentry/sentry:24.8.0
sentry-ingest-monitors-6b89cdb4f7-5ttw5	getsentry/sentry:24.8.0
sentry-ingest-occurrences-7d7dbf948f-xfdxf	getsentry/sentry:24.8.0
sentry-ingest-replay-recordings-68ffdf8d85-f85vw	getsentry/sentry:24.8.0
sentry-issue-occurrence-consumer-5fcb74d78-h526g	getsentry/snuba:24.8.0
sentry-kafka-controller-0	docker.io/bitnami/kafka:3.7.1-debian-12-r4
sentry-kafka-controller-1	docker.io/bitnami/kafka:3.7.1-debian-12-r4
sentry-kafka-controller-2	docker.io/bitnami/kafka:3.7.1-debian-12-r4
sentry-metrics-consumer-64cb5969ff-lc9gx	getsentry/sentry:24.8.0
sentry-nginx-86d6c867f8-2rd5w	docker.io/bitnami/nginx:1.27.2-debian-12-r0
sentry-post-process-forward-errors-bcdd9bcbb-zdkjt	getsentry/sentry:24.8.0
sentry-post-process-forward-issue-platform-5585db5b95-xnhxj	getsentry/sentry:24.8.0
sentry-post-process-forward-transactions-cc7ff69cc-mzlwh	getsentry/sentry:24.8.0
sentry-rabbitmq-0	docker.io/bitnami/rabbitmq:3.11.18-debian-11-r0
sentry-relay-cd9fbf484-lmxxm	getsentry/relay:24.8.0
sentry-sentry-postgresql-0	docker.io/bitnami/postgresql:15.3.0-debian-11-r0
sentry-sentry-redis-master-0	docker.io/bitnami/redis:7.0.11-debian-11-r12
sentry-sentry-redis-replicas-0	docker.io/bitnami/redis:7.0.11-debian-11-r12
sentry-snuba-api-6c674b6797-b4jxv	getsentry/snuba:24.8.0
sentry-snuba-consumer-b9b8b9dd8-b9pzl	getsentry/snuba:24.8.0
sentry-snuba-generic-metrics-counters-consumer-6c565457f8-mfnd2	getsentry/snuba:24.8.0
sentry-snuba-generic-metrics-distributions-consumer-64d78fvr56f	getsentry/snuba:24.8.0
sentry-snuba-generic-metrics-sets-consumer-58dc8b9494-sw54h	getsentry/snuba:24.8.0
sentry-snuba-group-attributes-consumer-7cc6bc9fdd-pr922	getsentry/snuba:24.8.0
sentry-snuba-metrics-consumer-c98596579-vhp8q	getsentry/snuba:24.8.0
sentry-snuba-outcomes-billing-consumer-7cc6d455bb-tx8lv	getsentry/snuba:24.8.0
sentry-snuba-outcomes-consumer-78b859867f-lfvln	getsentry/snuba:24.8.0
sentry-snuba-replacer-fd9545b5c-fv2cz	getsentry/snuba:24.8.0
sentry-snuba-replays-consumer-77555c647c-xp5v8	getsentry/snuba:24.8.0
sentry-snuba-spans-consumer-f85597476-kf2jk	getsentry/snuba:24.8.0
sentry-snuba-subscription-consumer-events-59cfd68856-cwts4	getsentry/snuba:24.8.0
sentry-snuba-subscription-consumer-metrics-d4f645879-dzpst	getsentry/snuba:24.8.0
sentry-snuba-subscription-consumer-transactions-854cf7dfc4dbgjk	getsentry/snuba:24.8.0
sentry-snuba-transactions-consumer-68d5f86dfd-h5n46	getsentry/snuba:24.8.0
sentry-subscription-consumer-events-644f989f99-cgmgw	getsentry/sentry:24.8.0
sentry-subscription-consumer-generic-metrics-858f45d868-sw8ph	getsentry/sentry:24.8.0
sentry-subscription-consumer-metrics-665b79b996-bfd24	getsentry/sentry:24.8.0
sentry-subscription-consumer-transactions-7645d86cdc-wzltk	getsentry/sentry:24.8.0
sentry-web-7ccd66948-rvmtr	getsentry/sentry:24.8.0
sentry-worker-79669599cc-fptgc	getsentry/sentry:24.8.0
sentry-zookeeper-clickhouse-0	docker.io/bitnami/zookeeper:3.8.2-debian-11-r27
```

**Comment by bmassemin** [comment]
@patsevanton I deploy with flux, but I didn't noticed that the chart was in a failed state, I restarted the deployment and now it's fine.

**Comment by Mokto** [comment]
Ok let's maybe make the next release a major one then?

**Pull request merged**
