### PR TITLE
Resolve Safari Content-Disposition header bug

### PR DESCRIPTION
**Pull request by sijmenvos**
Related : https://github.com/getsentry/self-hosted/pull/2297

After adding this line to nginx config + redeploy of nginx deployment it seems to work again

### CODE REVIEW

**Comment by Mokto** [comment]
Can you update the patch version of the chart at the same time please ? 

Thanks.

**Comment by sijmenvos** [comment]
Done!

**Comment by xvilo** [comment]
It can also be temporarily fixed through something like https://github.com/sentry-kubernetes/charts/issues/1017#issuecomment-1761191761

**Comment by Mokto** [comment]
I'm closing this PR as it is pretty old. Feel free to resolve the conflicts and I'll take a look at it again.

**Pull request closed without merging**
