### PR TITLE
Add liveness probe to worker deployment

### LINKED ISSUE #463: No liveness probe for Sentry workers
It would be nice to have a liveness probe that checks if the Celery workers are still working as expected.

I will provide a simple probe in a PR that uses the `ping` API of Celery to validate that everything works as intended for further discussion if this makes sense and how it should be implemented

### PR DESCRIPTION
**Pull request by prskr**
Closes #463

### CODE REVIEW

**Comment by z0rc** [comment]
@baez90 please make this configurable. In my testing this liveness check is way slower than current `timeoutSeconds`. It takes around 45 seconds to return.

**Comment by prskr** [comment]
Can do so in a follow up PR 😅

Edit: @z0rc do you have a RabbitMQ cluster running? I noticed that if I'm running the setup with a clustered RabbitMQ the workers often don't process anything after some time. One of the reasons for this PR, I moved to a single RabbitMQ server to get rid of this...

**Comment by z0rc** [comment]
@baez90 I don't use RabbitMQ. My configuration relies in AWS managed Kafka.

**Comment by prskr** [comment]
Interesting, I will make the timeout configurable in the next week!

**Comment by hippoz** [comment]
**my sentry-worker pods frequently restarts after this change, which is good in 11.6.0. I have created an issue [here](https://github.com/sentry-kubernetes/charts/issues/477)**

 -------------- celery@sentry-eks-worker-687fbf45d-kgkw9 v4.4.7 (cliffs)
--- ***** -----
-- ******* ---- Linux-5.4.129-63.229.amzn2.x86_64-x86_64-with-debian-10.10 2021-09-11 09:55:06
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         sentry:0x7fcc5994ef98
- ** ---------- .> transport:   amqp://guest:**@sentry-eks-rabbitmq:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> activity.notify  exchange=default(direct) key=activity.notify
                .> alerts           exchange=default(direct) key=alerts
                .> app_platform     exchange=default(direct) key=app_platform
                .> appstoreconnect  exchange=default(direct) key=sentry.tasks.app_store_connect.#
                .> assemble         exchange=default(direct) key=assemble
                .> auth             exchange=default(direct) key=auth
                .> buffers.process_pending exchange=default(direct) key=buffers.process_pending
                .> cleanup          exchange=default(direct) key=cleanup
                .> code_owners      exchange=default(direct) key=code_owners
                .> commits          exchange=default(direct) key=commits
                .> counters-0       exchange=counters(direct) key=default
                .> data_export      exchange=default(direct) key=data_export
                .> default          exchange=default(direct) key=default
                .> digests.delivery exchange=default(direct) key=digests.delivery
                .> digests.scheduling exchange=default(direct) key=digests.scheduling
                .> email            exchange=default(direct) key=email
                .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
                .> events.process_event exchange=default(direct) key=events.process_event
                .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
                .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
                .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
                .> events.reprocessing.symbolicate_event exchange=default(direct) key=events.reprocessing.symbolicate_event
                .> events.save_event exchange=default(direct) key=events.save_event
                .> events.symbolicate_event exchange=default(direct) key=events.symbolicate_event
                .> files.delete     exchange=default(direct) key=files.delete
                .> group_owners.process_suspect_commits exchange=default(direct) key=group_owners.process_suspect_commits
                .> incident_snapshots exchange=default(direct) key=incident_snapshots
                .> incidents        exchange=default(direct) key=incidents
                .> integrations     exchange=default(direct) key=integrations
                .> merge            exchange=default(direct) key=merge
                .> options          exchange=default(direct) key=options
                .> relay_config     exchange=default(direct) key=relay_config
                .> releasemonitor   exchange=default(direct) key=releasemonitor
                .> reports.deliver  exchange=default(direct) key=reports.deliver
                .> reports.prepare  exchange=default(direct) key=reports.prepare
                .> search           exchange=default(direct) key=search
                .> sleep            exchange=default(direct) key=sleep
                .> stats            exchange=default(direct) key=stats
                .> subscriptions    exchange=default(direct) key=subscriptions
                .> triggers-0       exchange=triggers(direct) key=default
                .> unmerge          exchange=default(direct) key=unmerge
                .> update           exchange=default(direct) key=update

/usr/local/lib/python3.6/site-packages/sentry/utils/strings.py:45: DeprecationWarning: invalid escape sequence '\['
  "unicode-escape", "unicode-escape-recovery"
/usr/local/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
09:55:10 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
09:58:01 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
09:58:01 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')

worker: Warm shutdown (MainProcess)

**Comment by hippoz** [comment]
root@sentry-eks-worker-75457c4d6f-25fbv:/# sentry exec -c 'import celery, os; dest="celery@{}".format(os.environ["HOSTNAME"]); print(celery.task.control.ping(destination=[dest], timeout=5)[0][dest]["ok"])'
12:12:04 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
12:12:06 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "<string>", line 7, in <module>
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 7, in <module>
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 197, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/exec.py", line 118, in exec_
    exec(compile(script, file, "exec"), g, g)
  File "<string>", line 11, in <module>
__main__.ScriptError: Failed to execute script '<string>'

**Comment by hippoz** [comment]
https://gitmemory.com/issue/celery/celery/4079/470935560

**Comment by prskr** [comment]
I see, I'll make the liveness probe itself optional and opt-out it per default so that everyone can give it a try and dependent on their environment disable it again for now until I'm able to come up with a better solution that is not so load dependent and more stable.

Just out of curiosity:  do you notice a throughput decrease caused by having the workers restarted so often? I'm just wondering because initially before creating this PR I was playing around with some options to see if at least having the workers restarting every once in a while stabilizes my processing due to the fact that they at least don't get stuck... :sweat_smile:  quite desperate I know but I had to get it working at least at a 'staging' level...

**Comment by sagor999** [comment]
Re: worker stability
You probably have something misconfigured somewhere. Our workers are processing on average about 100k-200k events per day and are up for more than 2 weeks at a time (then they are restarted as part of GKE cluster upgrade that happens every 2 weeks or so). But maybe your workload is also much bigger and we are simply not seeing the issue that you might be observing as well. :thinking:

**Comment by prskr** [comment]
I'm actually thinking my problem might be contrary caused because we do not process a lot of events (probably 1000 a day).

@sagor999 you are also using Kafka for Celery queue or are you using a RabbitMQ cluster - still looking for someone who's using RabbitMQ in the hope of getting some advice 😅

**Comment by sagor999** [comment]
We are using Kafka and Redis. Not using RabbitMQ.

**Comment by hippoz** [comment]
we are using Kafaka, rabbitMQ and redis as well. yes, our worker pods are sometimes just hanging up and stopped processing more events. I thought a proper liveness probe is necessary for this. I currently have a workaround for this is to rollout restart the worker deployment blindly with a gitlab scheduled ci job.

**Comment by prskr** [comment]
Great to hear that I'm not totally dumb :smile: scheduled CI job is a smart idea!
Especially considering the fact that a liveness probe is apparently not that easy to implement...I will give Redis/KeyDB as queue backend a shot to see if the workers are more stable in such a configuration.

**Comment by avznog** [comment]
Had the same problem, consider increasing the livenessProbe `timeoutSeconds`, as the command for the probe takes a lot of time.

**Pull request merged**
