### PR TITLE
ci: fix workflows lint & test

### PR DESCRIPTION
**Pull request by TartanLeGrand**
This PR introduces significant improvements to our GitHub Actions workflow to optimize the process for linting and testing our Helm charts. 🚀

#### Key Changes:
- 🧹 **Streamlined Workflow**: Refined the steps in our CI pipeline to reduce redundancy. This includes better handling of environment variables and outputs.
- 🔧 **Fixed Chart Directory Issues**: Corrected the chart directory, ensuring that `ct list-changed` and `ct lint` operate on the correct directories.

#### Expected Benefits:
- 🛠️ **Enhanced Reliability**: More accurate linting and testing will help prevent issues from making it to production, boosting our overall deployment reliability.
- 📊 **Better Visibility**: The debug enhancements will provide deeper insights into the CI process, making it easier to identify and fix issues early.

#### Looking Forward:
- I plan to monitor the impact of these changes on our CI performance closely and will make further adjustments as needed based on the outcomes.

#### Request for Feedback:
- 🔄 I'm open to suggestions on how to further refine our CI pipeline and would love to hear about any additional tools or practices that could be integrated to improve our workflow.

Thank you for reviewing these workflow enhancements! Your feedback is invaluable as we continue to improve our CI/CD processes. 🌟

### CODE REVIEW

**Comment by TartanLeGrand** [comment]
:eyes: Merge this before continue the #1343

**Comment by Mokto** [comment]
I'm afraid this will break a lot of things.

`release-please-config.json` I'm pretty sure you have to change, but I think there will be a few others.

**Comment by TartanLeGrand** [comment]
> I'm afraid this will break a lot of things.
> 
> `release-please-config.json` I'm pretty sure you have to change, but I think there will be a few others.

Yes, you have right !

I have do this in this PR:

https://github.com/sentry-kubernetes/charts/pull/1343/files#diff-c55d4dcb68c348b2c06d263819702fbce72eeeb35b662956d02049a5a18fcf2b

I go to fix !

**Comment by Mokto** [comment]
You are also missing a change in the deployment workflow.

**Comment by Mokto** [comment]
The tests are failing.

**Comment by TartanLeGrand** [comment]
> The tests are failing.

Yes because the chart is already broken :smile: :

https://github.com/sentry-kubernetes/charts/issues/1315

**Comment by Mokto** [comment]
Ok then i'll merge it and wait for your changes on the 24.6.0 branch

**Comment by Mokto** [comment]
@TartanLeGrand https://github.com/sentry-kubernetes/charts/pull/1357 the release flow is broken.

**Pull request merged**
