### PR TITLE
Add new required service accounts

### LINKED ISSUE #805: Missing ServiceAccounts for new components
@pavels @Mokto 

Followup to https://github.com/sentry-kubernetes/charts/pull/800.

`billing-metrics-consumer`, `ingest-metrics-consumer-perf` and `ingest-metrics-consumer-rh` require corresponding ServiceAccount when `serviceAccount.enabled=true` is set.

I'm creating this issue so it won't get lost. I'll try to create a PR for this once I get some free time, but for now please feel free to take over.

### PR DESCRIPTION
**Pull request by DanielMcAssey**
Adds the missing service accounts fixes #805

### CODE REVIEW

**Review by Mokto — APPROVED** [review]

**Comment by spectrogram** [comment]
@DanielMcAssey to fix the lint issue you'll need to rebase so that you get the updated Chart.yaml from upstream. It was fixed in this commit: https://github.com/sentry-kubernetes/charts/blob/9fe1b754628e46215d74d28171221ed7bec5513d/sentry/Chart.yaml

**Comment by z0rc** [comment]
@Mokto @DanielMcAssey any way to move the PR forward and merge it? Do you need assistance?

**Comment by DanielMcAssey** [comment]
I'll get on it today

**Comment by dixneuf19** [comment]
Hi @DanielMcAssey could we move on with this PR ? We are also impacted with this issue on our Sentry cluster, and the fix _seems_ straightforward and riskless.

Thanks for your contribution !

**Comment by DanielMcAssey** [comment]
Apologies for the delay. This has now been rectified. @Mokto would it be possible to merge this?

**Comment by z0rc** [comment]
@Mokto please merge this.

**Comment by DanielMcAssey** [comment]
Updated to fix version again

**Comment by Mokto** [comment]
Sorry I completely missed this PR.

**Comment by DanielMcAssey** [comment]
Thank you!

**Pull request merged**
