### PR TITLE
feat: history limits for cronjobs

### PR DESCRIPTION
**Pull request by nishaero**
Adding customizability to cronjobs history limits gives us more flexibility during debugging.

The initial values are set to 5 for each respectively, this would allow more logs to be stored. Which could help in debugging.

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks. You have conflicts due to your other PR that I merged this morning!

**Comment by nishaero** [comment]
Fixed the conflicts, its ready for merge now 👍

**Comment by Mokto** [comment]
Not anymore ;)

**Comment by nishaero** [comment]
got that fixed as well 👍

**Pull request merged**
