### PR TITLE
Adding statsd backend + prometheus-operator support

### LINKED ISSUE #81: Metrics Support
From the previous chart there was support for statsd/prometheus via 

https://github.com/helm/charts/pull/14355

Is there any plans for this type of 'native' integration in this chart? a-la `metrics.enabled=true`?

### PR DESCRIPTION
**Pull request by ts-mini**
There are _some_ changes to the readme - i can either back these out or keep going. it just kinda is a pain :P - but metrics work for our installation and figured i'd share
Fixes https://github.com/sentry-kubernetes/charts/issues/81

### CODE REVIEW

**Comment by joscha-alisch** [comment]
I did test this by the way and it works great, even have it running in our production cluster now - a merge would be highly appreciated :)

**Review by Mokto — APPROVED** [review]

**Comment by Mokto** [comment]
Nice, could you please upgrade the minor version of the chart ?

Thanks!

**Comment by Mokto** [comment]
(Sorry for the late reply)

**Comment by ts-mini** [comment]
> Nice, could you please upgrade the minor version of the chart ?
> 
> Thanks!

@Mokto Should be good to go, bumped minor from 0.3.0 -> 0.4.0

**Comment by Mokto** [comment]
I think there was some confusion here (maybe because of the name of the chart).
You have to update the `sentry` chart, not `sentry-kubernetes`.

**Comment by ts-mini** [comment]
@Mokto :facepalm: my bad - was obviously not paying attention

**Comment by Mokto** [comment]
Thanks for your work on this!

**Pull request merged**
