### PR TITLE
Fix for metrics alerts not firing

### PR DESCRIPTION
**Pull request by sagor999**
Fixes this: https://github.com/sentry-kubernetes/charts/issues/388
Based on PR: https://github.com/getsentry/onpremise/pull/735

It uses `--auto-offset-reset=latest` as in original PR from onpremise, though in this PR https://github.com/sentry-kubernetes/charts/pull/446/files all of them were switched to `earliest` instead. Not sure which one is the right one here.

### CODE REVIEW

**Comment by rajudivakaran** [comment]
Can we please merge this one ?

**Comment by cleveritcz** [comment]
when I tried this I got these errors:

```
kubectl logs sentry-subscription-consumer-events-7fdbbb68b7-rvsft -n sentry
Usage: sentry run query-subscription-consumer [OPTIONS]
Try 'sentry run query-subscription-consumer --help' for help.

Error: no such option: --topic events-subscription-results
```

```
kubectl logs sentry-subscription-consumer-transactions-bb5879ff8-kk67q -n sentry
Usage: sentry run query-subscription-consumer [OPTIONS]
Try 'sentry run query-subscription-consumer --help' for help.

Error: no such option: --topic transactions-subscription-results
```

**Comment by sagor999** [comment]
@cleveritcz what sentry version you were using when you tried this?

**Comment by sagor999** [comment]
@cleveritcz ah, found an issue. Should be fixed now.

**Comment by cleveritcz** [comment]
Thanks. It is working now. :)

**Comment by rajudivakaran** [comment]
@sagor999 Do you know when could this be possible merged ? We are using the chart as a proxy chart and only maintaining a values file for our sentry running in k8s cluster.

**Comment by sagor999** [comment]
@rajudivakaran whenever @Mokto will be around to approve and merge this request.

**Comment by Mokto** [comment]
11.7.0 should allow you to set the value you want.

**Comment by sagor999** [comment]
@Mokto a bit confused by your comment. I think you might have replied to a wrong thread? Also, this has not been merged so not going to be in 11.7.0
Edit: oh, I think you are referring to `auto-offset-reset` change. I will update my PR :)

**Comment by sagor999** [comment]
@Mokto updated with recent changes.

**Comment by sagor999** [comment]
@Mokto just checking if you have anything outstanding that would prevent you from merging this?

**Comment by Mokto** [comment]
Merging it now, sorry for the delay!

**Pull request merged**
