### PR TITLE
feat(clickhouse): update ClickHouse version to 23.3.19.32

### PR DESCRIPTION
**Pull request by patsevanton**
## Description
@Mokto  This pull request updates the ClickHouse version in the Helm chart to 23.3.19.32. The new version aligns with with the upgrade script located at [install/upgrade-clickhouse.sh](https://github.com/getsentry/self-hosted/blob/master/install/upgrade-clickhouse.sh).

## Changes
Updated the appVersion in the Chart.yaml file from 22.8.15.23 to 23.3.19.32.

Update plan:
sentry  clickhouse
24.7.1  21.8.13.6
24.8.0  23.3.19.32
24.9.0  23.3.19.32

## Related Issues
- #1474

## Related Pull Requests:
- #1540

i tested sentry 24.8.0 and clickhouse chart version 3.12.0 with 22.8.15.23
sentry-snuba-migrate-pkpmh snuba-migrate snuba.clickhouse.errors.ClickhouseError: DB::Exception: Codec DoubleDelta does not accept any arguments. Stack trace:

i tested sentry 24.8.0 and clickhouse version 23.3.19.32 - no errors

### CODE REVIEW

**Comment by adonskoy** [comment]
Do we need to update the clickhouse version sequentially? If so, then it should have been a new major version

**Comment by patsevanton** [comment]
I think yes
https://github.com/getsentry/self-hosted/blob/master/install/upgrade-clickhouse.sh#L20
Which clickhouse version do you mean?

I think the upgrade plan will be like this:
sentry clickhouse
24.7.1 21.8.13.6
24.7.1 22.8.15.23
24.7.1 23.3.19.32
24.8.0 23.3.19.32
24.9.0 23.3.19.32

**Comment by Mokto** [comment]
So let's update to Clickhouse on a minor/patch first [3.12.0](https://github.com/sentry-kubernetes/charts/releases/tag/clickhouse-v3.12.0)

And then to 3.13.0 on a major?

**Comment by patsevanton** [comment]
@Mokto Do you mean like https://github.com/sentry-kubernetes/charts/pull/1556 ?

**Comment by adonskoy** [comment]
It looks like it is possible to update clickhouse directly to the latest major version, but it is recommended to shutdown the cluster before doing so

https://clickhouse.com/docs/en/operations/update#incremental-upgrades

**Comment by adonskoy** [comment]
We can release a new major version of the sentry chart with an updated version of clickhouse and leave a recommendation in the readme to set the number of clickhouse replicas to 0 before updating

**Pull request merged**
