### PR TITLE
Upgrading Kafka to Bitnami 2.6.0

### PR DESCRIPTION
**Pull request by DandyDeveloper**
Worth noting I've only tried this in a test clutser. Id like to get another person to test if they can. 

My specific concern is upgrades. 

This is important because it increases stability and consumer productivity. 

fixes
- #239

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
Please excuse all the commits, my fork was very far behind.

**Comment by DandyDeveloper** [comment]
@Mokto I've tested this in a prod environment. No issues with the upgrade, no changes needed to the base values yaml. Think we're good to merge this.

**Comment by Mokto** [comment]
Cool! I'll check it on my production environment too

**Comment by Mokto** [comment]
Works flawlessly for me!

**Pull request merged**
