### PR TITLE
Fix cleanup job

### PR DESCRIPTION
**Pull request by alekitto**
Related to #356
 
I misinterpreted a commit from `onpremise` repo, so there was an error on the cleanup cronjob. This should revert the erroneous change.
Also, I noted that snuba cleanup jobs are not present. Should I add them?

### CODE REVIEW

**Comment by Mokto** [comment]
Sure, would be nice! ;)

**Comment by alekitto** [comment]
Ok @Mokto, added the snuba cleanup cronjobs. I copied the interval from the `onpremise` repo, but IMHO it is a little too frequent. What do you think about it?

**Comment by Mokto** [comment]
I don't know how that works internally but yeah that seems extreme. Maybe every hour then ?

**Comment by alekitto** [comment]
> Maybe every hour then ?

Seems reasonable, I've updated the default values accordingly

**Comment by zifeo** [comment]
This will fix #362

**Pull request merged**
