### PR TITLE
added support for geoip database mounting

### PR DESCRIPTION
**Pull request by pulse00**

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks for your PR!

Looks fine but you seem to have code from https://github.com/sentry-kubernetes/charts/pull/667 in your PR.

**Comment by pulse00** [comment]
> Thanks for your PR!
> 
> Looks fine but you seem to have code from #667 in your PR.

i fixed the conflicts.

**Comment by pulse00** [comment]
not sure why the chart linter fails though, @Mokto

**Comment by Mokto** [comment]
Need a version bump so that's it's deployed automatically.

15.1.0

Thanks!

**Comment by pulse00** [comment]
sorry, i'm new to helm :sweat_smile:  - bumped the version but no i have another linter error, but no indication where the problem is

```
Error: [trailing-spaces] trailing spaces
```

**Review by Mokto — APPROVED** [review]

**Comment by z0rc** [comment]
@pulse00 can you also update documentation with example how user can prepare volume with GeoIP DB?

**Pull request merged**
