### PR TITLE
Support HPA container resource

### PR DESCRIPTION
**Pull request by kimxogus**
Autoscaling v2 has been GA since k8s 1.23.
Container resource is enabled if k8s version is >= 1.27

### CODE REVIEW

**Comment by adonskoy** [comment]
It seems to me that this change needs to be released as a new major version, and also in the README, indicate the minimum version of kubernetes with which this chart can be used.

You can also add kubeVersion to Chart.yaml. You can specify `kubeVersion: >=1.23`

**Comment by kimxogus** [comment]
@adonskoy I added backward compatibility for k8s < 1.23 because I think this change is not big enough to bump a major version.

**Comment by kimxogus** [comment]
@adonskoy Could you review this?

**Review by ushuz — APPROVED** [review]

**Comment by kimxogus** [comment]
@Mokto Could you merge this?

**Review by Mokto — APPROVED** [review]

**Pull request merged**
