### PR TITLE
update snuba config for 23.2.0

### PR DESCRIPTION
**Pull request by ntcong**

### CODE REVIEW

**Comment by reneeckstein** [comment]
Hi @ntcong, I also just upgraded our Sentry to 23.2.0 and Clickhouse 20.12.8.5

It went well with only one small issue: snuba replacer no longer supports the option `--max-batch-size` so it should be removed from the container command in deployment-snuba-replacer.yaml.

```
2023-02-22 23:49:11,888 Initializing Snuba...
2023-02-22 23:49:13,993 Snuba initialization took 2.1045433609979227s
Usage: snuba replacer [OPTIONS]
Try 'snuba replacer --help' for help.

Error: No such option: --max-batch-size
```

**Comment by ntcong** [comment]
> It went well with only one small issue: snuba replacer no longer supports the option `--max-batch-size` so it should be removed from the container command in deployment-snuba-replacer.yaml.

Oh I actually forgot about that, will update it here.

**Comment by Mokto** [comment]
hey, your PR seems quite nice, could you please do the required changes ? Thanks ;)

**Comment by farodin91** [comment]
@ntcong I did some updates for 23.3.1.

**Comment by z0rc** [comment]
This PR superseded by https://github.com/sentry-kubernetes/charts/pull/849 and https://github.com/sentry-kubernetes/charts/pull/832. Can be closed.

**Pull request closed without merging**
