### PR TITLE
Update sentry to 24.1.1

### PR DESCRIPTION
**Pull request by farodin91**

### CODE REVIEW

**Comment by farodin91** [comment]
@Mokto Would you like to review?

**Review by Mokto — APPROVED** [review]
LGTM but I'm waiting for a few days to see if everything work as intended on my cluster.

**Comment by Mokto** [comment]
Screenshot 2024-01-31 at 20 16 12

**Comment by farodin91** [comment]
@Mokto  It should be fixed now.

**Comment by hd-deman** [comment]
faced with same problem (https://github.com/getsentry/self-hosted/issues/2728) after upgrade to 24.1.1 

so we also need to support
this:
https://github.com/getsentry/self-hosted/pull/2722/files
here:
https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/configmap-sentry.yaml#L146

It worked for me, but I don't want to create additional PR

**Comment by farodin91** [comment]
@hd-deman  updated.

**Comment by Mokto** [comment]
Thanks!

**Pull request merged**
