### PR TITLE
Add affinity, nodeSelector to user-create job

### PR DESCRIPTION
**Pull request by DongjinS**
Hi 👋 

I struggled with user-create job that has no nodeSelector, because I use a eks cluster of two different node groups(arm64+amd64).

So I want to add affinity, nodeSelector to user-create job.
Thank you.

> I referred to the issues and PR below
- https://github.com/sentry-kubernetes/charts/issues/732
- https://github.com/sentry-kubernetes/charts/pull/394

### CODE REVIEW

**Comment by iscultas** [comment]
Hi @Mokto. This PR is beneficial. Can you review and merge it?

**Review by Mokto — APPROVED** [review]

**Comment by iscultas** [comment]
@DongjinS can you fix merge conflicts, please?

**Comment by DongjinS** [comment]
@iscultas @Mokto Thank you for your comments and reviews. I fixed the conflicts but now the lint is broken. 
Is there anything else I can do to merge?

**Comment by Mokto** [comment]
It's fine I'll merge it

**Pull request merged**
