### PR TITLE
Add ability to use a secret for the mail password

### LINKED ISSUE #764: get mail credentials from secret
For better security I want to store my credentials in a secret, not in the values file.

### PR DESCRIPTION
**Pull request by DanielMcAssey**
Adds the ability to use mail secret instead of password in plaintext, closes #764

I redid the PR to match the refactored .env

### CODE REVIEW

**Comment by DanielMcAssey** [comment]
@Mokto Does this look ok?

**Comment by Mokto** [comment]
Sure, that's fine! 

Can you please upgrade to 17.3.0?

**Comment by Mokto** [comment]
Ok 17.4.0 now

**Comment by DanielMcAssey** [comment]
Bumped version!

**Pull request merged**
