### PR TITLE
added sentry-relay-init job to only generate relay credentials once after installation

### PR DESCRIPTION
**Pull request by pulse00**
This PR removes the init-container from the relay pod and replaces the logic with a post-install hook to only generate the credentials once after installation.

References https://github.com/sentry-kubernetes/charts/issues/666

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks for your PR. How would that work for new installations?

**Comment by Mokto** [comment]
Even for my current installation, my relay pods get stuck saying 
```
2022-07-18T05:12:03Z [relay_log::utils] ERROR: relay has no credentials, which are required in managed mode. Generate some with "relay credentials generate" first.
```

**Comment by pulse00** [comment]
> Thanks for your PR. How would that work for new installations?

good point - unfortunately `relay credentials generate` will exit with an error if the credentials already exist and i found no option to exit with a different error code. 

Maybe we should override the command with a custom entry point script, check if the credentials.json already exists and only run the built in entry-point if it does not exist? then it could run as post-install and post-upgrade hook.

**Comment by pulse00** [comment]
@Mokto i pushed a change that creates a configmap with a script which will check if the credentials are already present. it will do nothing if they are, but will generate them if they are not present.

**Comment by Mokto** [comment]
I don't think this scales properly, you won't be able to mount the PVC to more than 1 container.

**Comment by pulse00** [comment]
> I don't think this scales properly, you won't be able to mount the PVC to more than 1 container.

you're right. i refactored the PR to not use a PVC and be backwards compatible. It's possible to provide `relay.existingSecret` with a pre-generated credentials.json - if that exists, the initPod will not generate new credentials but copy over the existing ones from the secret.

**Comment by Danielss89** [comment]
+1 for this one. Atm. we need to "register" the relay again and again if relay pod is deleted, as it will create new credentials on each new deploy

**Comment by nklmilojevic** [comment]
Following up on this one. Is there a possibility for someone to review and merge it?

**Comment by Mokto** [comment]
I'm closing this PR as it's really old. Feel free to reopen it if needed.

**Pull request closed without merging**
