### PR TITLE
Feat/sentry ingest consumer

### PR DESCRIPTION
**Pull request by yoan-adfinis**
This pull request enables relay and the ingest-consumer on the current version of Sentry. A follow up of #137 (and #130)

**NB** this seems to work on a fresh install but I've seen some 403 when doing an upgrade from the current version. :confused:

### CODE REVIEW

**Comment by yoan-adfinis** [comment]
@Mokto this version includes the `nginx`  for internal cluster usage I guess. I'm assuming many things are missing if this was to be used within the cluster.

**Comment by Mokto** [comment]
Lgtm ! 
I would add some notes in the readme to explain why we need nginx (explaining that we should either use nginx, either the ingress).

Thanks for your work on this ;)

**Comment by Mokto** [comment]
& change the version to 5.0.0 ;)

**Comment by Mokto** [comment]
@yoan-adfinis 
I'm taking the liberty to add a commit to your branch. Hope that's fine?
I'm leaving for vacations tomorrow (2 weeks), so I'd like this PR to be merged today ;) 

Redis connection is not working with external redis (probably it's the same for kafka, I'll try)

**Comment by yoan-adfinis** [comment]
> Hope that's fine?

Absolutely.

> I'm leaving for vacations tomorrow

Same same, kind of. I already wish you some great time off.

**Comment by Mokto** [comment]
@yoan-adfinis can you check my commit ?
I think everything is working fine now :)

Enjoy your vacations too!

**Pull request merged**
