### PR TITLE
Sentry November release

### PR DESCRIPTION
**Pull request by adonskoy**

### CODE REVIEW

**Review by Mokto — APPROVED** [review]

**Comment by z0rc** [comment]
After this PR `sentry-snuba-db-init` fails with:
```
2023-11-16 11:29:47,517 Initializing Snuba...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/src/snuba/snuba/cli/__init__.py", line 58, in get_command
    initialize.initialize_snuba()
  File "/usr/src/snuba/snuba/core/initialize.py", line 41, in initialize_snuba
    _load_storages()
  File "/usr/src/snuba/snuba/core/initialize.py", line 21, in _load_storages
    from snuba.datasets.storages.factory import initialize_storage_factory
  File "/usr/src/snuba/snuba/datasets/storages/factory.py", line 13, in <module>
    from snuba.datasets.storages.validator import StorageValidator
  File "/usr/src/snuba/snuba/datasets/storages/validator.py", line 6, in <module>
    from snuba.migrations.groups import get_group_readiness_state_from_storage_set
  File "/usr/src/snuba/snuba/migrations/groups.py", line 141, in <module>
    StorageSetKey.GENERIC_METRICS_GAUGES,
  File "/usr/src/snuba/snuba/clusters/storage_sets.py", line 33, in __getattr__
    raise AttributeError(attr)
AttributeError: GENERIC_METRICS_GAUGES
```

Probably you missed https://github.com/getsentry/snuba/pull/4888

**Comment by adonskoy** [comment]
Oh, sorry. I forgot to add this file to the commit.

@Mokto, hot fix for this issue https://github.com/sentry-kubernetes/charts/pull/1069

**Comment by jeremiebelaid** [comment]
Hello,
I don't understand why the 2 snuba sessions deployements are being removed, now the events are pilling in kafka.
Am I missing something?

**Comment by adonskoy** [comment]
> Hello, I don't understand why the 2 snuba sessions deployements are being removed, now the events are pilling in kafka. Am I missing something?

sessions has been deprecated and metrics are now used instead

**Comment by phihos** [comment]
Hi,

so according to [this issue](https://github.com/getsentry/self-hosted/issues/2200) Sentry already uses the `metrics` table in Clickhouse right? Is there any need for Sentry to write into the `ingest-sessions` topic? And if not how can we turn it off?

**Pull request merged**
