### PR TITLE
Remove extra quotation mark in ConfigMap

### PR DESCRIPTION
**Pull request by GoIT-FCC**
Due to this quotation mark, GitHub integration does not work, Sentry fails with "Could not deserialize key data" error

### CODE REVIEW

**Review by kilhage — APPROVED** [review]

**Comment by GoIT-FCC** [comment]
@Mokto Please, review this change as it blocks our work

**Comment by Mokto** [comment]
Sorry about the delay.

I had to add this hack, without it doesn't work.

This works for me :

```

  github:
    appId: "1234"
    appName: MyApp
    clientId: "yyy"
    clientSecret: "XXX"
    privateKey: "-----BEGIN RSA PRIVATE KEY-----\nAAAAAAA\BBBBB==\n-----END RSA PRIVATE KEY-----\n"
    webhookSecret: "XXXX"
```

**Comment by GoIT-FCC** [comment]
@Mokto could you try with my latest changes? It works for me, but it doesn't work with your hack with extra quotation

**Comment by Mokto** [comment]
Trying now. Thanks!

**Pull request merged**
