### PR TITLE
docs: added golang example for generating exception

### PR DESCRIPTION
**Pull request by patsevanton**
#### Description
This pull request adds a Golang example for generating exceptions and sending them to Sentry. The example includes a simple Golang application that generates various types of custom errors and sends them to Sentry for monitoring and analysis. The changes also include updates to the `Dockerfile` and `README.md` to provide clear instructions for building and deploying the Golang application.

#### Changes Made
- **Golang Example:** Added a Golang example in the `main.go` file that demonstrates how to generate different types of custom errors and send them to Sentry.
- **Dockerfile Updates:** Added comments to the `Dockerfile` explaining each step of the Docker image build process.
- **README.md Updates:** Added instructions to the `README.md` file for building the Docker image, uploading it to Docker Hub, creating a Kubernetes Secret, and deploying the application to Kubernetes.
- **Kubernetes Configuration:** Added comments to the `sentry-benchmark.yaml` and `sentry-dsn.yaml` files to clarify the Kubernetes deployment and Secret configuration.

#### Why This Change is Necessary
Providing a clear and practical example for generating exceptions in Golang is essential for users who want to integrate Sentry into their Golang applications. This example will help users understand how to set up error handling and monitoring in their Golang projects, making it easier to detect and resolve issues.

---
Feel free to review and provide feedback. Thank you!

### CODE REVIEW

**Comment by Mokto** [comment]
I like the idea but I think we should deploy the docker image to a public location so that it's easier to use?

**Comment by patsevanton** [comment]
Yes, but where?

**Comment by Mokto** [comment]
Any docker hub repo or any github packages repo I would say

**Comment by patsevanton** [comment]
@Mokto Is it possible to make a separate repository for the golang example?

**Comment by Mokto** [comment]
Sure! Why don't you create one yourself ? ;)

**Comment by Mokto** [comment]
Oh and it would be nice if that image was multi-arch

**Comment by patsevanton** [comment]
I can`t create repository in org https://github.com/sentry-kubernetes
Did you mean to create a repository in my personal github account?
What does multi-arch mean?

**Comment by Mokto** [comment]
I meant on your personal account but actually I created a repo for you with write access: https://github.com/sentry-kubernetes/golang-test-image


I meant that we need to build & deploy the image for at least x86_64, amd64 and arm64 if possible.

**Comment by patsevanton** [comment]
@Mokto created https://github.com/sentry-kubernetes/golang-test-image
the version is changed by Conventional Commits

**Pull request closed without merging**
