### PR TITLE
Revert "Allow for v0 API endpoints (#757)"

### PR DESCRIPTION
**Pull request by xvilo**
This reverts commit b04aed78076a87cbb7090569f87ff40a84f1216d.

It didn't fully work, and ultimately broke more

### CODE REVIEW

**Comment by Mokto** [comment]
Hi & thanks! 

Could you please upgrade the chart version too?

**Comment by xvilo** [comment]
@Mokto done!

**Comment by xvilo** [comment]
@Mokto are you able to create a new release for it?

**Comment by Mokto** [comment]
It's done automatically. The chart has been released to 17.7.1

**Pull request merged**
