### PR TITLE
feat: upd templates

### PR DESCRIPTION
**Pull request by paulDashkevich**
- upd templates
- add new events_ string for migrations from 24.8.0 version

### CODE REVIEW

**Comment by paulDashkevich** [comment]
I can't resolve confilicts
`Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.`

**Comment by patsevanton** [comment]
Hi!
Please don't change the following files:
charts/sentry/Chart.lock
charts/sentry/Chart.yaml
It is better to edit these files separately

**Comment by paulDashkevich** [comment]
> Hi! Please don't change the following files: charts/sentry/Chart.lock charts/sentry/Chart.yaml It is better to edit these files separately

ofc, this is my all files from fork
but the idea is clear - add updates to templates.
I apologize, but I have never done PR for forks in my practice and I don’t know how to fix PR

**Comment by Mokto** [comment]
You can create either revert those specific changes or create a new PR.

**Pull request closed without merging**
