### PR TITLE
fix: empty email values were crashing the pods

### LINKED ISSUE #6: Chart doesn't work if mail settings are not set
Hi it fails when you leave defaults empty on this error.

```
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 270, in validate_option
    raise TypeError("%r: got %r, expected %r" % (key, _type(value), opt.type))
TypeError: 'mail.username': got <type 'NoneType'>, expected string
```

### PR DESCRIPTION
**Pull request by Mokto**
Fix #6

### CODE REVIEW

**Comment by Mokto** [comment]
@voslartomas does it fix it for you ? ;)

**Comment by voslartomas** [comment]
Can you create new version? Or how do you test this out in a branch? And also one question, how do you release new version (where is it stored?)?

**Comment by Mokto** [comment]
I would prefer to test it before creating a new version.

To test it I usually have a parent chart containing this one:
```
dependencies:
  - name: sentry-db
    version: 0.6.0
    repository: file://../../../charts/sentry-db
```

Something like that ;)

---

To answer your other question, Github Actions is automatically pushing everything that is on develop, to that branch : https://github.com/sentry-kubernetes/charts/tree/gh-pages. And that's deployed to https://sentry-kubernetes.github.io/charts through Github Pages.

Only thing we need to do to deploy a new version is to change the version in the Chart.yaml file.

Thanks!

**Comment by voslartomas** [comment]
@Mokto Tested, works!

**Comment by Mokto** [comment]
Thanks ! I'll push it tonight.

**Comment by voslartomas** [comment]
@Mokto what about tonight? Will you push it :)

**Comment by Mokto** [comment]
Forgot about this, sorry. Pushing it now.

**Pull request merged**
