### PR TITLE
Sentry 22.7.0

### PR DESCRIPTION
**Pull request by z0rc**
https://github.com/getsentry/self-hosted/releases/tag/22.7.0

With this release sentry started to test ARM support and switched Clickhouse to version 21 on ARM. Worth checking out both options and plan clickhouse upgrade.

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks! Have you tried running the migrations? It didn't work properly for me.

**Comment by z0rc** [comment]
@Mokto not yet. I don't have spare installation to do full cycle of testing.

**Comment by z0rc** [comment]
I did check self-hosted diff between 22.6.0 and 22.7.0 and didn't notice any "infrastructure" changes. Also I checked opened issues in self-hosted repo, no problems were reported.

It's been more than 2 weeks after release, no bug fixes or pending PRs.

**Comment by LukeCarrier** [comment]
I think the Clickhouse migrations fail because of a missing `generic_metrics_distributions` storage set. See getsentry/snuba#2899.

```diff
diff --git a/sentry/templates/configmap-snuba.yaml b/sentry/templates/configmap-snuba.yaml
index b41d9c3..a112dde 100644
--- a/sentry/templates/configmap-snuba.yaml
+++ b/sentry/templates/configmap-snuba.yaml
@@ -44,6 +44,7 @@ data:
             "errors_v2_ro",
             "profiles",
             "replays",
+            "generic_metrics_distributions",
             "generic_metrics_sets",
         },
         {{- /*
```

**Comment by z0rc** [comment]
@LukeCarrier nice catch, thanks! I updated the PR.

**Comment by z0rc** [comment]
@Mokto are you able to check, whether adding new storage set fixes migrations for you?

**Comment by Mokto** [comment]
Just tried it now, all seems fine! I'll probably merge tomorrow for safety.

Thanks!

**Comment by Mokto** [comment]
Thanks!

**Pull request merged**
