### PR TITLE
feat: added issue occurence consumer

### PR DESCRIPTION
**Pull request by Mokto**

### CODE REVIEW

**Comment by adonskoy** [comment]
@Mokto, it is not very clear what this consumer will do?

**Comment by Mokto** [comment]
Have no idea tbh, I just wanted to make sure we match what's in the onpremise repository.

**Comment by adonskoy** [comment]
This is a component for 23.8.0, which is not yet released, not the current version

**Comment by Mokto** [comment]
Good to know.

**Comment by stevenyongzion** [comment]
Should this go together with https://github.com/sentry-kubernetes/charts/pull/965?

**Comment by Mokto** [comment]
It's already part of it. I'll close.

**Pull request closed without merging**
