### PR TITLE
add pod labels to metrics

### PR DESCRIPTION
**Pull request by colton-4g**
#1029

### CODE REVIEW

**Comment by colton-4g** [comment]
@adonskoy Would you be able to take a look at this?

**Comment by adonskoy** [comment]
> @adonskoy Would you be able to take a look at this?

Looks good, but I'm not a maintainer

**Comment by colton-4g** [comment]
> > @adonskoy Would you be able to take a look at this?
> 
> Looks good, but I'm not a maintainer

Sorry, maybe @Mokto ?

**Comment by Mokto** [comment]
Thanks! Please update the chart version.

**Comment by colton-4g** [comment]
@Mokto Done!

**Pull request merged**
