### PR TITLE
Service annotations for sentry web and relay

### PR DESCRIPTION
**Pull request by sfc-gh-pkommini**
Moving sentry-web service level annotations to `.Values.relay.service.annotations` and sentry-relay service level annotations to `.Values.sentry.web.service.annotations` as per the `aws-load-balancer-controller` [documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/).

### CODE REVIEW

**Comment by sfc-gh-pkommini** [comment]
@Mokto Let me know if this works.

**Comment by Mokto** [comment]
I'm fine with it, but could you please upgrade the major version ?
It's a breaking change for everyone.

**Comment by sfc-gh-pkommini** [comment]
Will. Also is it okay if I provide an example in the docs based on my experiments with the chart for how to run this on AWS EKS?

**Comment by sfc-gh-pkommini** [comment]
@Mokto Upgraded the version to 13.0.0. Thank you for your prompt response.

**Comment by Mokto** [comment]
Thanks! And yes please do add an example.

The documentation is quite bad right now.

**Comment by sfc-gh-pkommini** [comment]
@Mokto Pushed some changes let me know if you can merge. Thank you 🙏

**Comment by Mokto** [comment]
Thanks! Sorry I just realized but could you also please add a note: 
```
## Upgrading from 12.x.x version of this Chart to 13.0.0
```

And then we're good to go :)

**Comment by sfc-gh-pkommini** [comment]
Updated.

**Comment by sfc-gh-pkommini** [comment]
Seems like there were some unintended formatting changes on the YAML files. That's due to auto-formatting employed by VS code. Those changes are only cosmetic.

**Review by Mokto — APPROVED** [review]

**Comment by Mokto** [comment]
Thanks a lot!

**Pull request merged**
