### PR TITLE
chore: added a note for nginx ingress controller

### PR DESCRIPTION
**Pull request by Mokto**

### CODE REVIEW

**Review by DandyDeveloper — COMMENTED** [review]
Could we enabled enable these automatically if `xyz.ingress.enabled` = True?

**Comment by odoucet** [comment]
> Could we enabled enable these automatically if `xyz.ingress.enabled` = True?

Nope, because nginx may not be the default ingress in the k8s cluster. 

Adding comments si good enough and will help user :)

**Comment by DandyDeveloper** [comment]
@odoucet Sure, but you could look at the annotation value... There's a lot of nice ways you could achieve this.

**Comment by Mokto** [comment]
I'll merge it like that for now, but it can definitely be improved.

**Pull request merged**
