### PR TITLE
Update Sentry app version to 24.6.0

### PR DESCRIPTION
**Pull request by xvilo**
- Update app version
- Update chart version

### CODE REVIEW

**Comment by Mokto** [comment]
Have you tried the version yourself?

**Comment by xvilo** [comment]
I have not, if you want it, I can try and apply an update locally tomorrow

**Comment by TartanLeGrand** [comment]
Hello :wave:,

I'm currently working on fixing the version issues we're experiencing. The release 24.6.0 introduces a breaking change for US, specifically related to Kafka topics creation.

I plan to create a PR either today or tomorrow to address these issues:

- [Issue #1315](https://github.com/sentry-kubernetes/charts/issues/1315)
- [Issue #1333](https://github.com/sentry-kubernetes/charts/issues/1333)

Additionally, I'm hopeful that the Kafka BC will resolve the relay issue we're seeing in [Issue #1250](https://github.com/sentry-kubernetes/charts/issues/1250).

Thank you! :blush:

**Comment by Mokto** [comment]
Amazing, thanks!

**Comment by morsik** [comment]
Heya! Any update on this? ;)

**Comment by patsevanton** [comment]
PR implement by https://github.com/sentry-kubernetes/charts/pull/1454

**Pull request closed without merging**
