### PR TITLE
Allow some snuba deployments to be pushed as hooks

### PR DESCRIPTION
**Pull request by mariusmitrofanbostontr**

### CODE REVIEW

**Comment by mariusmitrofanbostontr** [comment]
@Mokto do you mind if you push this change too please?

I hate having to scale down / up replicas.

The default functionality is to leave it "as it was" anyway :)

**Comment by Mokto** [comment]
I'm thinking maybe we should combine asHook with the relay one.

So having one "asHook" for everything.

What do you think ?

**Comment by mariusmitrofanbostontr** [comment]
Sounds good to me :)

Updated!

**Comment by Mokto** [comment]
Thanks ! Could you remove the version bump?
I'm going to apply another fix + change the major version!

**Comment by mariusmitrofanbostontr** [comment]
Sure, done

**Pull request merged**
