### PR TITLE
ci: configure renovate to only create patch update prs

### PR DESCRIPTION
**Pull request by patsevanton**
#### Changes:

This pull request configures Renovate to create only Pull Request for patch updates (patch updates). This will help reduce the number of automatically created PRs and focus on the most critical updates.

#### Details:

- **renovate.json**:
  - Added configuration in `packageRules` to ensure that Renovate creates PRs only for patch updates.
  - This change helps streamline the update process by focusing on smaller, less disruptive updates.

Please review and merge if everything looks good.

Thanks!

### CODE REVIEW

**Comment by Mokto** [comment]
I would still like to get notifications on major upgrades.

Maybe we should just run the job once a month for major upgrades?

**Comment by patsevanton** [comment]
May be https://docs.renovatebot.com/configuration-options/#schedule
But how update minor version?
May be major update by hand and minor update every month? 
```
{
  "extends": ["config:recommended", ":rebaseStalePrs", "docker:disable"],
  "enabled": true,
  "prConcurrentLimit": 30,
  "enabledManagers": ["helmv3", "github-actions"],
  "schedule": [
    "before 5am on Monday"
  ],
  "packageRules": [
    {
      "updateTypes": ["patch"],
      "schedule": [
        "before 5am on Monday"
      ]
    },
    {
      "updateTypes": ["major"],
      "schedule": [
        "before 5am on the first day of the month"
      ]
    }
  ]
}

```

**Comment by Mokto** [comment]
That's good! Minor can follow the same logic as patch.

**Comment by patsevanton** [comment]
https://github.com/sentry-kubernetes/charts/pull/1436

**Pull request closed without merging**
