### PR TITLE
feat: bump sentry dependencies

### PR DESCRIPTION
**Pull request by kimxogus**
I've checked compatibility of bitnami's common chart between sentry's dependencies.

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks! Have you run that update against the "default" (more or less) chart settings?

**Comment by kimxogus** [comment]
@Mokto I have checked diff without my own values.yaml (`helm diff sentry SENTRY_PATH -n sentry`) with [diff plugin](https://github.com/databus23/helm-diff).

**Comment by Mokto** [comment]
Thanks. Could you please write upgrade notes here: https://github.com/sentry-kubernetes/charts/blob/develop/README.md

Explaining you've upgraded subcharts + version of the helm yaml

**Comment by kimxogus** [comment]
@Mokto Sorry for late. I wrote upgrade notes.

**Review by Mokto — APPROVED** [review]

**Pull request merged**
