### PR TITLE
Make Slack secret key configurable

### PR DESCRIPTION
**Pull request by ushuz**
Make `slack` secret key like `client-id` configurable, similar to `github` and `google`.

Supersede and close #1035: This pull request is more up-to-date and also updates `values.yaml`.

### CODE REVIEW

**Comment by ushuz** [comment]
Close as duplicate of #1035

**Comment by ushuz** [comment]
Reopen as this is more up-to-date than #1035. This also updates `values.yaml` comments.

**Comment by patsevanton** [comment]
@Mokto Please close PR by https://github.com/sentry-kubernetes/charts/pull/1035

**Comment by Mokto** [comment]
Thanks!

**Pull request closed without merging**
