### PR TITLE
feat: add value to enable/disable init of ClickHouse

### PR DESCRIPTION
**Pull request by minijus**
When running in restricted OpenShift environment we were getting this error from `initContainer`:
```
mkdir: can't create directory '/etc/clickhouse-server/': Permission denied
```

Trying to remove the `initContainer` completely yielded in no error and the pods started successfully. It seem that the `initContainer` is not needed (or at least no longer needed for some later version of ClickHouse).

### CODE REVIEW

**Comment by Mokto** [comment]
Hey, thanks for your PR.

What is the purpose of it?

**Comment by minijus** [comment]
Hi @Mokto,

I've updated description of this PR to include some details and reasoning why I did it.

**Comment by pauvos** [comment]
Really good, can we merge this please?

The busybox init container doesn't work with PodSecurityPolicies (runAsUser > 0) enabled. I can confirm that clickhouse starts perfectly without it - at least a recent [clickhouse/clickhouse-server](https://hub.docker.com/r/clickhouse/clickhouse-server) version.

It appears the yandex repo is deprecated? https://github.com/sentry-kubernetes/charts/issues/67#issuecomment-1104118407

**Comment by Mokto** [comment]
Hey guys, thanks for your PR.

If we don't need it anymore, why don't we remove the container entirely?

**Comment by pauvos** [comment]
@Mokto I think you are right and it can be dropped. Since there is no volume mounted to `/etc/` it probably doesn't do anything.

Concering clickhouse: the latest clickhouse/clickhouse-server version (22.x) starts but doesn't seem to work with sentry (missing  schema migrations not running). I found a workaround for yandex/clickhouse-server and will leave a comment in #67 .

**Comment by Mokto** [comment]
I'm closing this PR as it's really old. Feel free to reopen it if needed.

**Pull request closed without merging**
