### PR TITLE
fix: replay session

### PR DESCRIPTION
**Pull request by TartanLeGrand**
Add all configuration for replay session and let enable by default

### CODE REVIEW

**Comment by acjohnson** [comment]
+1 but does this actually make Session Replays "just work"? We get a blank "video" when we try to watch the session replay back... Maybe we are doing something wrong still...

**Comment by TartanLeGrand** [comment]
> +1 but does this actually make Session Replays "just work"? We get a blank "video" when we try to watch the session replay back... Maybe we are doing something wrong still...

We get blank too, I start to add all features and will see next :smile:

**Comment by Mokto** [comment]
Thanks. Could you please update to 20.8.3?

**Comment by TartanLeGrand** [comment]
@Mokto good 😄

**Pull request merged**
