### PR TITLE
fix: external db

### PR DESCRIPTION
**Pull request by Mokto**

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@Mokto Since we'll be having contributors now, can you drop my name for review? Getting a second pair of eyes never hurts.

**Comment by Mokto** [comment]
Sure, you're right.

**Comment by Mokto** [comment]
What's your timezone? I thought you were in the US

**Comment by Mokto** [comment]
Ohh, Japan

**Comment by DandyDeveloper** [comment]
@mokto Japan for now!

**Pull request merged**
