### PR TITLE
Change default relay mode to managed.

### PR DESCRIPTION
**Pull request by Antiarchitect**
Use relay managed mode by default in order to fix:
https://github.com/getsentry/sentry/issues/22789
https://github.com/getsentry/sentry/issues/23161

### CODE REVIEW

**Comment by ckoehn** [comment]
I was about to make the same PR. Sentry does basically no data scrubbing with the current defaults!

**Comment by Mokto** [comment]
Let me try it today but I had a lot of issues previously with this mode.

**Comment by Antiarchitect** [comment]
It's about a week we turned this mode on for our corporate Sentry - all is OK for now. Rate Limits and DSN checking now works at last.

**Comment by Mokto** [comment]
Thanks!

**Pull request merged**
