### PR TITLE
allow using externalPostgresql.existingSecret to inject password

### PR DESCRIPTION
**Pull request by orezi**
Addresses #613 to add an existing secret that holds postgresql-password

### CODE REVIEW

**Comment by Agalin** [comment]
What's the point of keeping password in external Postgres values? It should be completely removed IMO as it's a terrible practice. Also `existingSecretKey` is missing from `values.yaml`.

Any chance for this to be merged and released?

**Comment by AndrMoiseev** [comment]
> What's the point of keeping password in external Postgres values? It should be completely removed IMO as it's a terrible practice. Also `existingSecretKey` is missing from `values.yaml`.
> 
Totally agree.

> Any chance for this to be merged and released?

Same question. I was actually going to make PR of my own)

**Comment by echel0n** [comment]
will this be merged in soon?

**Review by Mokto — APPROVED** [review]

**Comment by Mokto** [comment]
LGTM can you upgrade the minor version of the chart please?

**Comment by Mokto** [comment]
Can you rebase please?

**Comment by andrewhearin** [comment]
Would love to see this get merged!

**Comment by echel0n** [comment]
will this be in the next release ?

**Comment by begemotik** [comment]
@orezi @Mokto would appreciate if you don't leave the PR half way through. Would appreciate this merged!

**Comment by begemotik** [comment]
@orezi thank you!
@Mokto all green, is there anything else preventing from merging it?

**Comment by echel0n** [comment]
should `existingSecretKey` be specified in the chart values as well ?

**Comment by Mokto** [comment]
On vacation for the next 2 weeks. Sorry guys. I can just say I saw one change I didn’t like: upgrading appVersion in this PR.

**Review by Mokto — APPROVED** [review]

**Pull request merged**
