### PR TITLE
feat: offset-reset in ds

### PR DESCRIPTION
**Pull request by paulDashkevich**

### CODE REVIEW

**Comment by patsevanton** [comment]
I think need add comment with noStrictOffsetReset values.yaml

**Comment by paulDashkevich** [comment]
Yes, Anton. I'd remembered that after commit.

**Review by Mokto — APPROVED** [review]

**Comment by adonskoy** [comment]
It would be nice if you added `--strict-offset-reset / --no-strict-offset-reset` and `--auto-offset-reset` for all missing places

`--strict-offset-reset / --no-strict-offset-reset` is missing in:
- deployment-sentry-ingest-monitors
- deployment-sentry-ingest-occurrences
- deployment-sentry-ingest-profiles
- deployment-sentry-ingest-replay-recordings
- deployment-sentry-billing-metrics-consumer
- deployment-sentry-metrics-consumer
- deployment-sentry-subscription-consumer-events
- deployment-sentry-subscription-consumer-generic-metrics
- deployment-sentry-subscription-consumer-metrics
- deployment-sentry-subscription-consumer-transactions

`--auto-offset-reset` is missing in:
- deployment-sentry-ingest-consumer-attachments
- deployment-sentry-ingest-consumer-events
- deployment-sentry-ingest-monitors
- deployment-sentry-ingest-occurrences
- deployment-sentry-ingest-profiles
- deployment-sentry-ingest-replay-recordings
- deployment-sentry-ingest-consumer-transactions
- deployment-sentry-billing-metrics-consumer
- deployment-sentry-generic-metrics-consumer
- deployment-sentry-metrics-consumer
- deployment-sentry-post-process-forwarder-errors
- deployment-sentry-post-process-forwarder-issue-platform
- deployment-sentry-post-process-forwarder-transactions
- deployment-sentry-subscription-consumer-events
- deployment-sentry-subscription-consumer-generic-metrics
- deployment-sentry-subscription-consumer-metrics
- deployment-sentry-subscription-consumer-transactions

**Comment by adonskoy** [comment]
Oh, it was already merged. I'll make a separate PR then.

**Pull request merged**
