### PR TITLE
Use pod template for snuba

### PR DESCRIPTION
**Pull request by farodin91**
I would like to reduce the overhead to write deployments step by step.

### CODE REVIEW

**Comment by farodin91** [comment]
@Mokto  Would you like to review this PR?

**Comment by Mokto** [comment]
I'm not super confident on making that change. I feel like we're losing flexibility and more importantly, it's more prone to errors without a proper test suite.

**Comment by farodin91** [comment]
I will try to built a proper test suite for it. 

I tried to reduce the error prone behavior by moving everything into a single helper function.

**Comment by Mokto** [comment]
If you do that, that would be perfect 👍

**Comment by farodin91** [comment]
@Mokto  I added a basic idea for unittest. What do you think? 

My current concern only snuba-api tested. I would like to find a way to test all snuba without duplication.

**Comment by farodin91** [comment]
I could do a snapshot test this would require user manually review rendered data.

**Comment by Mokto** [comment]
I'd rather have snapshots so we know exactly what changes when anything changes in the repository.

Thanks!

**Comment by farodin91** [comment]
@Mokto  I added three snapshot tests. Should i add them for all deployments? Or should we split tests and helper changes.

**Comment by Mokto** [comment]
I'm closing this PR as it is pretty old. Feel free to resolve the conflicts and I'll take a look at it again.

**Pull request closed without merging**
