### PR TITLE
Partition count for subscription consumer transactions

### PR DESCRIPTION
**Pull request by z0rc**
snuba-subscription-consumer-transactions requires same fix as #566 when running with partitioned topic.

### CODE REVIEW

**Comment by sergeyshevch** [comment]
+1. Really need this fix

**Comment by sergeyshevch** [comment]
@Mokto Maybe you can look at this?

**Review by Mokto — APPROVED** [review]

**Comment by Mokto** [comment]
Can you please version bump it?

**Comment by z0rc** [comment]
@Mokto I'm confused, in other PR you said this can be skipped https://github.com/sentry-kubernetes/charts/pull/632#issuecomment-1140838211. I can version bump it, but what should be done about my other PR https://github.com/sentry-kubernetes/charts/pull/631.

**Comment by Mokto** [comment]
Yeah my bad i'll merge it ;)

**Comment by sergeyshevch** [comment]
@Mokto Can we make a release with this fix included?

**Comment by Mokto** [comment]
14.1.2 includes it.

**Pull request merged**
