### PR TITLE
FIX metrics alert not firing

### PR DESCRIPTION
**Pull request by marcomezzaro**
Pull request as requested for #388

### CODE REVIEW

**Comment by jadbaz** [comment]
Any word on having this merged?

**Comment by z0rc** [comment]
@Mokto ping

**Comment by onmomo** [comment]
We are also waiting for this. We have this running now with chart 14.0.2
* https://github.com/sentry-kubernetes/charts/pull/616

**Comment by z0rc** [comment]
@marcomezzaro does merged #616 fix your issue?

**Comment by marcomezzaro** [comment]
Sorry for the delay in responding, yes this fixed the issue.
image

**Comment by pyelulkar** [comment]
Hi,
Does this fix work for transaction, performance,apdex, throughput metric alerts?
regards,
PY

**Comment by onmomo** [comment]
> Hi,
> 
> Does this fix work for transaction, performance,apdex, throughput metric alerts?
> 
> regards,
> 
> PY

It works for our apdex and new issues alerts.

**Comment by pyelulkar** [comment]
@onmomo , Thanks for reply.
Any idea on - how can we enable performance alerts - throughput,transaction,failure rate metric alerts in on premise sentry ?
I have installed sentry on aws eks using helm chart.
regards,
PY

**Comment by pyelulkar** [comment]
Performance metrics alerts(throughput,transaction,failure rate) are working after adding this fix - https://github.com/getsentry/self-hosted/pull/739 
Can it be added to helm chart deployment templates?

**Pull request closed without merging**
