### PR TITLE
refactor: use stable cronjob

### PR DESCRIPTION
**Pull request by max-wittig**
avoids warnings

### CODE REVIEW

**Comment by max-wittig** [comment]
@Mokto WDYT?

**Comment by Mokto** [comment]
AFAIK this code would only work with Kubernetes 1.21?

**Comment by max-wittig** [comment]
That's true. Do you support Kubernetes versions across their whole lifetime? If so, then we can close this for the moment.

**Comment by Mokto** [comment]
You could use {{- if .Capabilities.APIVersions.Has "XXXX" }} to support all versions

**Comment by max-wittig** [comment]
Oh okay. Nice. I will look into this.

**Comment by Mokto** [comment]
I'm closing this PR as it's really old. Feel free to reopen it if needed.

**Pull request closed without merging**
